[package]
name = "hir-lowering"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = { workspace = true }
http = "0.2.9"
