[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
lexer = { path = "crates/01-lexer" }
parser = { path = "crates/02-parser" }
ast = { path = "crates/03-ast" }
hir = { path = "crates/06-hir" }
hir-lowering = { path = "crates/07-hir-lowering" }
session = { path = "crates/session" }
macros = { path = "crates/macros" }

ariadne = "0.3.0"
parking_lot = "0.12.1"
thin-vec = "0.2.12"
tracing = "0.1.37"

[patch.crates-io]
ariadne = { git = "https://github.com/MrNossiom/ariadne", branch = "main" }
