[workspace]
members = ["crates/*"]

[workspace.dependencies]
ast = { path = "crates/ast" }
ast-lowering = { path = "crates/ast-lowering" }
lexer = { path = "crates/lexer" }
docgen = { path = "crates/docgen" }
