[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ast = { path = "crates/ast" }
hir = { path = "crates/hir" }
hir-lowering = { path = "crates/hir-lowering" }
lexer = { path = "crates/lexer" }
macros = { path = "crates/macros" }
parser = { path = "crates/parser" }
session = { path = "crates/session" }

ariadne = "0.3.0"
parking_lot = "0.12.1"
thin-vec = "0.2.12"
tracing = "0.1.37"

[patch.crates-io]
ariadne = { git = "https://github.com/MrNossiom/ariadne", branch = "main" }
