[package]
name = "ast"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
session = { workspace = true }
lexer = { workspace = true }

thin-vec = { workspace = true }
