lints.workspace = true

[package]
name = "dapic_ast"
version = "0.0.0"
edition = "2021"

[dependencies]
dapic_session = { workspace = true }
dapic_lexer = { workspace = true }

thin-vec = { workspace = true }
