lints.workspace = true

[package]
name = "dapic_expand"
version = "0.0.0"
edition = "2021"

[dependencies]
dapic_ast = { workspace = true }
dapic_macros = { workspace = true }
dapic_parser = { workspace = true }
dapic_session = { workspace = true }

thin-vec = { workspace = true }
