lints.workspace = true

[package]
name = "expand"
version = "0.0.0"
edition = "2021"

[dependencies]
ast = { workspace = true }
macros = { workspace = true }
parser = { workspace = true }
session = { workspace = true }

thin-vec = { workspace = true }
