lints.workspace = true

[package]
name = "dapic_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
fastrand = "2"
proc-macro2 = "1"
quote = "1"
syn = "2"
synstructure = "0.13"
