lints.workspace = true

[package]
name = "dapic_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
fastrand = "2.0.0"
proc-macro2 = "1.0.66"
quote = "1.0.32"
syn = "2.0.28"
synstructure = "0.13.0"
