[package]
name = "macros"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[dependencies]
fastrand = "2.0.0"
proc-macro2 = "1.0.66"
quote = "1.0.32"
syn = "2.0.28"
synstructure = "0.13.0"
